// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMYpM4wJzfFjrEyraaIpWf2aiPv5xCAk',
    appId: '1:745911586980:web:9c8205099bd2a27de69631',
    messagingSenderId: '745911586980',
    projectId: 'chatty-955b0',
    authDomain: 'chatty-955b0.firebaseapp.com',
    databaseURL: 'https://chatty-955b0-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-955b0.appspot.com',
    measurementId: 'G-E96RHLVPYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh3YTCuJCCshzpdWjTQKGdUxBe8bytx-k',
    appId: '1:745911586980:android:1f22e00beebb603ce69631',
    messagingSenderId: '745911586980',
    projectId: 'chatty-955b0',
    databaseURL: 'https://chatty-955b0-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-955b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEYOFdf_qc64taA8e7Fo0GFCr0XwRr7jo',
    appId: '1:745911586980:ios:66400bf05d875f37e69631',
    messagingSenderId: '745911586980',
    projectId: 'chatty-955b0',
    databaseURL: 'https://chatty-955b0-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-955b0.appspot.com',
    iosBundleId: 'com.example.socialnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEYOFdf_qc64taA8e7Fo0GFCr0XwRr7jo',
    appId: '1:745911586980:ios:1dd636b24a15d717e69631',
    messagingSenderId: '745911586980',
    projectId: 'chatty-955b0',
    databaseURL: 'https://chatty-955b0-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-955b0.appspot.com',
    iosBundleId: 'com.example.socialnest.RunnerTests',
  );
}
